// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBnnhNAla3yH37ucJA3sanxwdAYVi7Ujg',
    appId: '1:991103430423:web:d8511f66c6347f8c8e5152',
    messagingSenderId: '991103430423',
    projectId: 'autorescue-b8564',
    authDomain: 'autorescue-b8564.firebaseapp.com',
    storageBucket: 'autorescue-b8564.appspot.com',
    measurementId: 'G-BY8G4F1EHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoBpEyozf5A46xJA96B6-RscxxZqXozCw',
    appId: '1:991103430423:android:db17480e3d0d04268e5152',
    messagingSenderId: '991103430423',
    projectId: 'autorescue-b8564',
    storageBucket: 'autorescue-b8564.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJE4_Rrkc_93ZKR4iaiWXg5jkyeO6VHFY',
    appId: '1:991103430423:ios:d1cb82bc5912f57e8e5152',
    messagingSenderId: '991103430423',
    projectId: 'autorescue-b8564',
    storageBucket: 'autorescue-b8564.appspot.com',
    iosBundleId: 'com.example.provider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJE4_Rrkc_93ZKR4iaiWXg5jkyeO6VHFY',
    appId: '1:991103430423:ios:01abd4f9fb195d828e5152',
    messagingSenderId: '991103430423',
    projectId: 'autorescue-b8564',
    storageBucket: 'autorescue-b8564.appspot.com',
    iosBundleId: 'com.example.provider.RunnerTests',
  );
}
